name: Run Python Code Every 2 Hours

on:
  schedule:
    - cron: '0 */2 * * *'

jobs:
  run-python-code:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Thay thế x bằng phiên bản Python bạn đang sử dụng

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Thay thế nếu bạn có một tệp requirements.txt

    - name: Run Python script
      run: python test.py  # Thay thế your_script.py bằng tên của đoạn mã Python bạn muốn chạy
